// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dealers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDealer = `-- name: CreateDealer :one
INSERT INTO dealers (name, slug, subdomain, logo_url, primary_color, secondary_color, contact_email, contact_phone, address)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, slug, subdomain, logo_url, primary_color, secondary_color, contact_email, contact_phone, address, active, created_at, updated_at
`

type CreateDealerParams struct {
	Name           string `json:"name"`
	Slug           string `json:"slug"`
	Subdomain      string `json:"subdomain"`
	LogoUrl        string `json:"logo_url"`
	PrimaryColor   string `json:"primary_color"`
	SecondaryColor string `json:"secondary_color"`
	ContactEmail   string `json:"contact_email"`
	ContactPhone   string `json:"contact_phone"`
	Address        string `json:"address"`
}

func (q *Queries) CreateDealer(ctx context.Context, arg CreateDealerParams) (Dealer, error) {
	row := q.db.QueryRow(ctx, createDealer,
		arg.Name,
		arg.Slug,
		arg.Subdomain,
		arg.LogoUrl,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Address,
	)
	var i Dealer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDealer = `-- name: DeleteDealer :exec
DELETE FROM dealers WHERE id = $1
`

func (q *Queries) DeleteDealer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDealer, id)
	return err
}

const getDealer = `-- name: GetDealer :one
SELECT id, name, slug, subdomain, logo_url, primary_color, secondary_color, contact_email, contact_phone, address, active, created_at, updated_at FROM dealers WHERE id = $1
`

func (q *Queries) GetDealer(ctx context.Context, id uuid.UUID) (Dealer, error) {
	row := q.db.QueryRow(ctx, getDealer, id)
	var i Dealer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDealerBySlug = `-- name: GetDealerBySlug :one
SELECT id, name, slug, subdomain, logo_url, primary_color, secondary_color, contact_email, contact_phone, address, active, created_at, updated_at FROM dealers WHERE slug = $1
`

func (q *Queries) GetDealerBySlug(ctx context.Context, slug string) (Dealer, error) {
	row := q.db.QueryRow(ctx, getDealerBySlug, slug)
	var i Dealer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDealerBySubdomain = `-- name: GetDealerBySubdomain :one
SELECT id, name, slug, subdomain, logo_url, primary_color, secondary_color, contact_email, contact_phone, address, active, created_at, updated_at FROM dealers WHERE subdomain = $1
`

func (q *Queries) GetDealerBySubdomain(ctx context.Context, subdomain string) (Dealer, error) {
	row := q.db.QueryRow(ctx, getDealerBySubdomain, subdomain)
	var i Dealer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDealers = `-- name: ListActiveDealers :many
SELECT id, name, slug, subdomain, logo_url, primary_color, secondary_color, contact_email, contact_phone, address, active, created_at, updated_at FROM dealers WHERE active = true ORDER BY name ASC
`

func (q *Queries) ListActiveDealers(ctx context.Context) ([]Dealer, error) {
	rows, err := q.db.Query(ctx, listActiveDealers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dealer{}
	for rows.Next() {
		var i Dealer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Subdomain,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.SecondaryColor,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.Address,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealers = `-- name: ListDealers :many
SELECT id, name, slug, subdomain, logo_url, primary_color, secondary_color, contact_email, contact_phone, address, active, created_at, updated_at FROM dealers ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListDealersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDealers(ctx context.Context, arg ListDealersParams) ([]Dealer, error) {
	rows, err := q.db.Query(ctx, listDealers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dealer{}
	for rows.Next() {
		var i Dealer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Subdomain,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.SecondaryColor,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.Address,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDealerActive = `-- name: SetDealerActive :exec
UPDATE dealers SET active = $2, updated_at = now() WHERE id = $1
`

type SetDealerActiveParams struct {
	ID     uuid.UUID `json:"id"`
	Active bool      `json:"active"`
}

func (q *Queries) SetDealerActive(ctx context.Context, arg SetDealerActiveParams) error {
	_, err := q.db.Exec(ctx, setDealerActive, arg.ID, arg.Active)
	return err
}

const updateDealer = `-- name: UpdateDealer :one
UPDATE dealers
SET name = $2, logo_url = $3, primary_color = $4, secondary_color = $5,
    contact_email = $6, contact_phone = $7, address = $8, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, subdomain, logo_url, primary_color, secondary_color, contact_email, contact_phone, address, active, created_at, updated_at
`

type UpdateDealerParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	LogoUrl        string    `json:"logo_url"`
	PrimaryColor   string    `json:"primary_color"`
	SecondaryColor string    `json:"secondary_color"`
	ContactEmail   string    `json:"contact_email"`
	ContactPhone   string    `json:"contact_phone"`
	Address        string    `json:"address"`
}

func (q *Queries) UpdateDealer(ctx context.Context, arg UpdateDealerParams) (Dealer, error) {
	row := q.db.QueryRow(ctx, updateDealer,
		arg.ID,
		arg.Name,
		arg.LogoUrl,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Address,
	)
	var i Dealer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
