// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countInventory = `-- name: CountInventory :one
SELECT count(*) FROM inventory WHERE dealer_id = $1
`

func (q *Queries) CountInventory(ctx context.Context, dealerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInventory, dealerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory (dealer_id, sku, name, description, category, unit, price, in_stock, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, dealer_id, sku, name, description, category, unit, price, in_stock, metadata, created_at, updated_at, version
`

type CreateInventoryItemParams struct {
	DealerID    uuid.UUID       `json:"dealer_id"`
	Sku         string          `json:"sku"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Category    string          `json:"category"`
	Unit        string          `json:"unit"`
	Price       string          `json:"price"`
	InStock     bool            `json:"in_stock"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.DealerID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Unit,
		arg.Price,
		arg.InStock,
		arg.Metadata,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Unit,
		&i.Price,
		&i.InStock,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory WHERE id = $1 AND dealer_id = $2
`

type DeleteInventoryItemParams struct {
	ID       uuid.UUID `json:"id"`
	DealerID uuid.UUID `json:"dealer_id"`
}

func (q *Queries) DeleteInventoryItem(ctx context.Context, arg DeleteInventoryItemParams) error {
	_, err := q.db.Exec(ctx, deleteInventoryItem, arg.ID, arg.DealerID)
	return err
}

const getInventoryBySKU = `-- name: GetInventoryBySKU :one
SELECT id, dealer_id, sku, name, description, category, unit, price, in_stock, metadata, created_at, updated_at, version FROM inventory WHERE dealer_id = $1 AND sku = $2
`

type GetInventoryBySKUParams struct {
	DealerID uuid.UUID `json:"dealer_id"`
	Sku      string    `json:"sku"`
}

func (q *Queries) GetInventoryBySKU(ctx context.Context, arg GetInventoryBySKUParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryBySKU, arg.DealerID, arg.Sku)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Unit,
		&i.Price,
		&i.InStock,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT id, dealer_id, sku, name, description, category, unit, price, in_stock, metadata, created_at, updated_at, version FROM inventory WHERE id = $1
`

func (q *Queries) GetInventoryItem(ctx context.Context, id uuid.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryItem, id)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Unit,
		&i.Price,
		&i.InStock,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listInventory = `-- name: ListInventory :many
SELECT id, dealer_id, sku, name, description, category, unit, price, in_stock, metadata, created_at, updated_at, version FROM inventory WHERE dealer_id = $1 ORDER BY name ASC LIMIT $2 OFFSET $3
`

type ListInventoryParams struct {
	DealerID uuid.UUID `json:"dealer_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListInventory(ctx context.Context, arg ListInventoryParams) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, listInventory, arg.DealerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inventory{}
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Unit,
			&i.Price,
			&i.InStock,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryByCategory = `-- name: ListInventoryByCategory :many
SELECT id, dealer_id, sku, name, description, category, unit, price, in_stock, metadata, created_at, updated_at, version FROM inventory WHERE dealer_id = $1 AND category = $2 ORDER BY name ASC
`

type ListInventoryByCategoryParams struct {
	DealerID uuid.UUID `json:"dealer_id"`
	Category string    `json:"category"`
}

func (q *Queries) ListInventoryByCategory(ctx context.Context, arg ListInventoryByCategoryParams) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, listInventoryByCategory, arg.DealerID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inventory{}
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Unit,
			&i.Price,
			&i.InStock,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchInventory = `-- name: SearchInventory :many
SELECT id, dealer_id, sku, name, description, category, unit, price, in_stock, metadata, created_at, updated_at, version FROM inventory
WHERE dealer_id = $1
  AND to_tsvector('english', name || ' ' || description) @@ plainto_tsquery('english', $2)
ORDER BY name ASC
LIMIT $3
`

type SearchInventoryParams struct {
	DealerID       uuid.UUID `json:"dealer_id"`
	PlaintoTsquery string    `json:"plainto_tsquery"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) SearchInventory(ctx context.Context, arg SearchInventoryParams) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, searchInventory, arg.DealerID, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inventory{}
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Unit,
			&i.Price,
			&i.InStock,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventoryItem = `-- name: UpdateInventoryItem :one
UPDATE inventory
SET name = $3, description = $4, category = $5, unit = $6, price = $7,
    in_stock = $8, metadata = $9, updated_at = now()
WHERE id = $1 AND dealer_id = $2 AND version = $10
RETURNING id, dealer_id, sku, name, description, category, unit, price, in_stock, metadata, created_at, updated_at, version
`

type UpdateInventoryItemParams struct {
	ID          uuid.UUID       `json:"id"`
	DealerID    uuid.UUID       `json:"dealer_id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Category    string          `json:"category"`
	Unit        string          `json:"unit"`
	Price       string          `json:"price"`
	InStock     bool            `json:"in_stock"`
	Metadata    json.RawMessage `json:"metadata"`
	Version     int32           `json:"version"`
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, updateInventoryItem,
		arg.ID,
		arg.DealerID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Unit,
		arg.Price,
		arg.InStock,
		arg.Metadata,
		arg.Version,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Unit,
		&i.Price,
		&i.InStock,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const upsertInventoryItem = `-- name: UpsertInventoryItem :one
INSERT INTO inventory (dealer_id, sku, name, description, category, unit, price, in_stock, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (dealer_id, sku) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    unit = EXCLUDED.unit,
    price = EXCLUDED.price,
    in_stock = EXCLUDED.in_stock,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, dealer_id, sku, name, description, category, unit, price, in_stock, metadata, created_at, updated_at, version
`

type UpsertInventoryItemParams struct {
	DealerID    uuid.UUID       `json:"dealer_id"`
	Sku         string          `json:"sku"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Category    string          `json:"category"`
	Unit        string          `json:"unit"`
	Price       string          `json:"price"`
	InStock     bool            `json:"in_stock"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) UpsertInventoryItem(ctx context.Context, arg UpsertInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, upsertInventoryItem,
		arg.DealerID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Unit,
		arg.Price,
		arg.InStock,
		arg.Metadata,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Unit,
		&i.Price,
		&i.InStock,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
