// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InputType string

const (
	InputTypeText  InputType = "text"
	InputTypeVoice InputType = "voice"
	InputTypeImage InputType = "image"
	InputTypePdf   InputType = "pdf"
)

func (e *InputType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InputType(s)
	case string:
		*e = InputType(s)
	default:
		return fmt.Errorf("unsupported scan type for InputType: %T", src)
	}
	return nil
}

type NullInputType struct {
	InputType InputType `json:"input_type"`
	Valid     bool      `json:"valid"` // Valid is true if InputType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInputType) Scan(value interface{}) error {
	if value == nil {
		ns.InputType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InputType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInputType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InputType), nil
}

type RequestStatus string

const (
	RequestStatusPending    RequestStatus = "pending"
	RequestStatusProcessing RequestStatus = "processing"
	RequestStatusParsed     RequestStatus = "parsed"
	RequestStatusConfirmed  RequestStatus = "confirmed"
	RequestStatusSent       RequestStatus = "sent"
	RequestStatusFailed     RequestStatus = "failed"
)

func (e *RequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatus(s)
	case string:
		*e = RequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatus: %T", src)
	}
	return nil
}

type NullRequestStatus struct {
	RequestStatus RequestStatus `json:"request_status"`
	Valid         bool          `json:"valid"` // Valid is true if RequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatus), nil
}

type UserRole string

const (
	UserRolePlatformAdmin UserRole = "platform_admin"
	UserRoleDealerAdmin   UserRole = "dealer_admin"
	UserRoleSalesRep      UserRole = "sales_rep"
	UserRoleContractor    UserRole = "contractor"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Dealer struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Subdomain      string             `json:"subdomain"`
	LogoUrl        string             `json:"logo_url"`
	PrimaryColor   string             `json:"primary_color"`
	SecondaryColor string             `json:"secondary_color"`
	ContactEmail   string             `json:"contact_email"`
	ContactPhone   string             `json:"contact_phone"`
	Address        string             `json:"address"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Inventory struct {
	ID          uuid.UUID          `json:"id"`
	DealerID    uuid.UUID          `json:"dealer_id"`
	Sku         string             `json:"sku"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Category    string             `json:"category"`
	Unit        string             `json:"unit"`
	Price       string             `json:"price"`
	InStock     bool               `json:"in_stock"`
	Metadata    json.RawMessage    `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Version     int32              `json:"version"`
}

type Request struct {
	ID              uuid.UUID          `json:"id"`
	DealerID        uuid.UUID          `json:"dealer_id"`
	ContractorID    uuid.UUID          `json:"contractor_id"`
	AssignedRepID   pgtype.UUID        `json:"assigned_rep_id"`
	Status          RequestStatus      `json:"status"`
	InputType       InputType          `json:"input_type"`
	RawText         string             `json:"raw_text"`
	MediaUrl        string             `json:"media_url"`
	StructuredItems json.RawMessage    `json:"structured_items"`
	AiConfidence    string             `json:"ai_confidence"`
	Notes           string             `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RetryCount      int32              `json:"retry_count"`
	LastError       string             `json:"last_error,omitempty"`
	Version         int32              `json:"version"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	DealerID            uuid.UUID          `json:"dealer_id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"-"`
	FullName            string             `json:"full_name"`
	Phone               string             `json:"phone"`
	Role                UserRole           `json:"role"`
	AssignedRepID       pgtype.UUID        `json:"assigned_rep_id"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
}
