// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignRequestToRep = `-- name: AssignRequestToRep :exec
UPDATE requests SET assigned_rep_id = $2, updated_at = now() WHERE id = $1
`

type AssignRequestToRepParams struct {
	ID            uuid.UUID   `json:"id"`
	AssignedRepID pgtype.UUID `json:"assigned_rep_id"`
}

func (q *Queries) AssignRequestToRep(ctx context.Context, arg AssignRequestToRepParams) error {
	_, err := q.db.Exec(ctx, assignRequestToRep, arg.ID, arg.AssignedRepID)
	return err
}

const countRequestsByDealer = `-- name: CountRequestsByDealer :one
SELECT count(*) FROM requests WHERE dealer_id = $1
`

func (q *Queries) CountRequestsByDealer(ctx context.Context, dealerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsByDealer, dealerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsByStatus = `-- name: CountRequestsByStatus :one
SELECT count(*) FROM requests WHERE dealer_id = $1 AND status = $2
`

type CountRequestsByStatusParams struct {
	DealerID uuid.UUID     `json:"dealer_id"`
	Status   RequestStatus `json:"status"`
}

func (q *Queries) CountRequestsByStatus(ctx context.Context, arg CountRequestsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsByStatus, arg.DealerID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (dealer_id, contractor_id, assigned_rep_id, input_type, raw_text, media_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version
`

type CreateRequestParams struct {
	DealerID      uuid.UUID   `json:"dealer_id"`
	ContractorID  uuid.UUID   `json:"contractor_id"`
	AssignedRepID pgtype.UUID `json:"assigned_rep_id"`
	InputType     InputType   `json:"input_type"`
	RawText       string      `json:"raw_text"`
	MediaUrl      string      `json:"media_url"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.DealerID,
		arg.ContractorID,
		arg.AssignedRepID,
		arg.InputType,
		arg.RawText,
		arg.MediaUrl,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.ContractorID,
		&i.AssignedRepID,
		&i.Status,
		&i.InputType,
		&i.RawText,
		&i.MediaUrl,
		&i.StructuredItems,
		&i.AiConfidence,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
		&i.LastError,
		&i.Version,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests WHERE id = $1
`

func (q *Queries) DeleteRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRequest, id)
	return err
}

const getRequest = `-- name: GetRequest :one
SELECT id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version FROM requests WHERE id = $1
`

func (q *Queries) GetRequest(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.ContractorID,
		&i.AssignedRepID,
		&i.Status,
		&i.InputType,
		&i.RawText,
		&i.MediaUrl,
		&i.StructuredItems,
		&i.AiConfidence,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
		&i.LastError,
		&i.Version,
	)
	return i, err
}

const listRequestsByContractor = `-- name: ListRequestsByContractor :many
SELECT id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version FROM requests WHERE contractor_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListRequestsByContractorParams struct {
	ContractorID uuid.UUID `json:"contractor_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListRequestsByContractor(ctx context.Context, arg ListRequestsByContractorParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequestsByContractor, arg.ContractorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.ContractorID,
			&i.AssignedRepID,
			&i.Status,
			&i.InputType,
			&i.RawText,
			&i.MediaUrl,
			&i.StructuredItems,
			&i.AiConfidence,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryCount,
			&i.LastError,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByDealer = `-- name: ListRequestsByDealer :many
SELECT id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version FROM requests WHERE dealer_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListRequestsByDealerParams struct {
	DealerID uuid.UUID `json:"dealer_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListRequestsByDealer(ctx context.Context, arg ListRequestsByDealerParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequestsByDealer, arg.DealerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.ContractorID,
			&i.AssignedRepID,
			&i.Status,
			&i.InputType,
			&i.RawText,
			&i.MediaUrl,
			&i.StructuredItems,
			&i.AiConfidence,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryCount,
			&i.LastError,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByRep = `-- name: ListRequestsByRep :many
SELECT id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version FROM requests WHERE assigned_rep_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListRequestsByRepParams struct {
	AssignedRepID pgtype.UUID `json:"assigned_rep_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) ListRequestsByRep(ctx context.Context, arg ListRequestsByRepParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequestsByRep, arg.AssignedRepID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.ContractorID,
			&i.AssignedRepID,
			&i.Status,
			&i.InputType,
			&i.RawText,
			&i.MediaUrl,
			&i.StructuredItems,
			&i.AiConfidence,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryCount,
			&i.LastError,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByStatus = `-- name: ListRequestsByStatus :many
SELECT id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version FROM requests WHERE dealer_id = $1 AND status = $2 ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListRequestsByStatusParams struct {
	DealerID uuid.UUID     `json:"dealer_id"`
	Status   RequestStatus `json:"status"`
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
}

func (q *Queries) ListRequestsByStatus(ctx context.Context, arg ListRequestsByStatusParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequestsByStatus,
		arg.DealerID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.ContractorID,
			&i.AssignedRepID,
			&i.Status,
			&i.InputType,
			&i.RawText,
			&i.MediaUrl,
			&i.StructuredItems,
			&i.AiConfidence,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryCount,
			&i.LastError,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequestRawText = `-- name: UpdateRequestRawText :exec
UPDATE requests SET raw_text = $2, updated_at = now() WHERE id = $1
`

type UpdateRequestRawTextParams struct {
	ID      uuid.UUID `json:"id"`
	RawText string    `json:"raw_text"`
}

func (q *Queries) UpdateRequestRawText(ctx context.Context, arg UpdateRequestRawTextParams) error {
	_, err := q.db.Exec(ctx, updateRequestRawText, arg.ID, arg.RawText)
	return err
}

const getRequestByDealer = `-- name: GetRequestByDealer :one
SELECT id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version FROM requests WHERE id = $1 AND dealer_id = $2
`

type GetRequestByDealerParams struct {
	ID       uuid.UUID `json:"id"`
	DealerID uuid.UUID `json:"dealer_id"`
}

func (q *Queries) GetRequestByDealer(ctx context.Context, arg GetRequestByDealerParams) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByDealer, arg.ID, arg.DealerID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.ContractorID,
		&i.AssignedRepID,
		&i.Status,
		&i.InputType,
		&i.RawText,
		&i.MediaUrl,
		&i.StructuredItems,
		&i.AiConfidence,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
		&i.LastError,
		&i.Version,
	)
	return i, err
}

const updateRequestNotesByDealer = `-- name: UpdateRequestNotesByDealer :exec
UPDATE requests SET notes = $2, updated_at = now() WHERE id = $1 AND dealer_id = $3
`

type UpdateRequestNotesByDealerParams struct {
	ID       uuid.UUID `json:"id"`
	Notes    string    `json:"notes"`
	DealerID uuid.UUID `json:"dealer_id"`
}

func (q *Queries) UpdateRequestNotesByDealer(ctx context.Context, arg UpdateRequestNotesByDealerParams) error {
	_, err := q.db.Exec(ctx, updateRequestNotesByDealer, arg.ID, arg.Notes, arg.DealerID)
	return err
}

const claimPendingRequests = `-- name: ClaimPendingRequests :many
UPDATE requests SET status = 'processing', updated_at = now()
WHERE id IN (
  SELECT id FROM requests
  WHERE status = 'pending'
  ORDER BY created_at ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version, version
`

func (q *Queries) ClaimPendingRequests(ctx context.Context, limit int32) ([]Request, error) {
	rows, err := q.db.Query(ctx, claimPendingRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.ContractorID,
			&i.AssignedRepID,
			&i.Status,
			&i.InputType,
			&i.RawText,
			&i.MediaUrl,
			&i.StructuredItems,
			&i.AiConfidence,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryCount,
			&i.LastError,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequestNotes = `-- name: UpdateRequestNotes :exec
UPDATE requests SET notes = $2, updated_at = now() WHERE id = $1
`

type UpdateRequestNotesParams struct {
	ID    uuid.UUID `json:"id"`
	Notes string    `json:"notes"`
}

func (q *Queries) UpdateRequestNotes(ctx context.Context, arg UpdateRequestNotesParams) error {
	_, err := q.db.Exec(ctx, updateRequestNotes, arg.ID, arg.Notes)
	return err
}

const updateRequestStatus = `-- name: UpdateRequestStatus :one
UPDATE requests
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version
`

type UpdateRequestStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status RequestStatus `json:"status"`
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) (Request, error) {
	row := q.db.QueryRow(ctx, updateRequestStatus, arg.ID, arg.Status)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.ContractorID,
		&i.AssignedRepID,
		&i.Status,
		&i.InputType,
		&i.RawText,
		&i.MediaUrl,
		&i.StructuredItems,
		&i.AiConfidence,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
		&i.LastError,
		&i.Version,
	)
	return i, err
}

const retryFailedRequests = `-- name: RetryFailedRequests :many
UPDATE requests SET status = 'pending', retry_count = retry_count + 1, updated_at = now()
WHERE id IN (
  SELECT id FROM requests
  WHERE status = 'failed' AND retry_count < $1
  ORDER BY updated_at ASC
  LIMIT $2
  FOR UPDATE SKIP LOCKED
)
RETURNING id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version
`

type RetryFailedRequestsParams struct {
	MaxRetries int32 `json:"max_retries"`
	Limit      int32 `json:"limit"`
}

func (q *Queries) RetryFailedRequests(ctx context.Context, arg RetryFailedRequestsParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, retryFailedRequests, arg.MaxRetries, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.ContractorID,
			&i.AssignedRepID,
			&i.Status,
			&i.InputType,
			&i.RawText,
			&i.MediaUrl,
			&i.StructuredItems,
			&i.AiConfidence,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryCount,
			&i.LastError,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRequestFailed = `-- name: SetRequestFailed :exec
UPDATE requests SET status = 'failed', last_error = $2, retry_count = retry_count, updated_at = now()
WHERE id = $1
`

type SetRequestFailedParams struct {
	ID        uuid.UUID `json:"id"`
	LastError string    `json:"last_error"`
}

func (q *Queries) SetRequestFailed(ctx context.Context, arg SetRequestFailedParams) error {
	_, err := q.db.Exec(ctx, setRequestFailed, arg.ID, arg.LastError)
	return err
}

const updateRequestStructuredItems = `-- name: UpdateRequestStructuredItems :one
UPDATE requests
SET structured_items = $2, ai_confidence = $3, status = 'parsed', updated_at = now()
WHERE id = $1
RETURNING id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version
`

type UpdateRequestStructuredItemsParams struct {
	ID              uuid.UUID       `json:"id"`
	StructuredItems json.RawMessage `json:"structured_items"`
	AiConfidence    string          `json:"ai_confidence"`
}

func (q *Queries) UpdateRequestStructuredItems(ctx context.Context, arg UpdateRequestStructuredItemsParams) (Request, error) {
	row := q.db.QueryRow(ctx, updateRequestStructuredItems, arg.ID, arg.StructuredItems, arg.AiConfidence)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.ContractorID,
		&i.AssignedRepID,
		&i.Status,
		&i.InputType,
		&i.RawText,
		&i.MediaUrl,
		&i.StructuredItems,
		&i.AiConfidence,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
		&i.LastError,
		&i.Version,
	)
	return i, err
}

const recoverStuckRequests = `-- name: RecoverStuckRequests :one
WITH recovered AS (
  UPDATE requests SET status = 'pending', last_error = 'recovered from stuck processing state', updated_at = now()
  WHERE status = 'processing' AND updated_at < now() - $1::interval
  LIMIT $2
  RETURNING id
)
SELECT count(*) FROM recovered
`

type RecoverStuckRequestsParams struct {
	StuckInterval string `json:"stuck_interval"`
	Limit         int32  `json:"limit"`
}

func (q *Queries) RecoverStuckRequests(ctx context.Context, arg RecoverStuckRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, recoverStuckRequests, arg.StuckInterval, arg.Limit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

// Version-checked update queries for optimistic concurrency control.

const updateRequestStatusVersioned = `-- name: UpdateRequestStatusVersioned :one
UPDATE requests
SET status = $2, updated_at = now()
WHERE id = $1 AND version = $3
RETURNING id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version
`

type UpdateRequestStatusVersionedParams struct {
	ID      uuid.UUID     `json:"id"`
	Status  RequestStatus `json:"status"`
	Version int32         `json:"version"`
}

func (q *Queries) UpdateRequestStatusVersioned(ctx context.Context, arg UpdateRequestStatusVersionedParams) (Request, error) {
	row := q.db.QueryRow(ctx, updateRequestStatusVersioned, arg.ID, arg.Status, arg.Version)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.ContractorID,
		&i.AssignedRepID,
		&i.Status,
		&i.InputType,
		&i.RawText,
		&i.MediaUrl,
		&i.StructuredItems,
		&i.AiConfidence,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
		&i.LastError,
		&i.Version,
	)
	return i, err
}

const updateRequestStructuredItemsVersioned = `-- name: UpdateRequestStructuredItemsVersioned :one
UPDATE requests
SET structured_items = $2, ai_confidence = $3, status = 'parsed', updated_at = now()
WHERE id = $1 AND version = $4
RETURNING id, dealer_id, contractor_id, assigned_rep_id, status, input_type, raw_text, media_url, structured_items, ai_confidence, notes, created_at, updated_at, retry_count, last_error, version
`

type UpdateRequestStructuredItemsVersionedParams struct {
	ID              uuid.UUID       `json:"id"`
	StructuredItems json.RawMessage `json:"structured_items"`
	AiConfidence    string          `json:"ai_confidence"`
	Version         int32           `json:"version"`
}

func (q *Queries) UpdateRequestStructuredItemsVersioned(ctx context.Context, arg UpdateRequestStructuredItemsVersionedParams) (Request, error) {
	row := q.db.QueryRow(ctx, updateRequestStructuredItemsVersioned, arg.ID, arg.StructuredItems, arg.AiConfidence, arg.Version)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.ContractorID,
		&i.AssignedRepID,
		&i.Status,
		&i.InputType,
		&i.RawText,
		&i.MediaUrl,
		&i.StructuredItems,
		&i.AiConfidence,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
		&i.LastError,
		&i.Version,
	)
	return i, err
}
