// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignContractorToRep = `-- name: AssignContractorToRep :exec
UPDATE users SET assigned_rep_id = $2, updated_at = now() WHERE id = $1
`

type AssignContractorToRepParams struct {
	ID            uuid.UUID   `json:"id"`
	AssignedRepID pgtype.UUID `json:"assigned_rep_id"`
}

func (q *Queries) AssignContractorToRep(ctx context.Context, arg AssignContractorToRepParams) error {
	_, err := q.db.Exec(ctx, assignContractorToRep, arg.ID, arg.AssignedRepID)
	return err
}

const assignContractorToRepByDealer = `-- name: AssignContractorToRepByDealer :exec
UPDATE users SET assigned_rep_id = $3, updated_at = now() WHERE id = $1 AND dealer_id = $2
`

type AssignContractorToRepByDealerParams struct {
	ID            uuid.UUID   `json:"id"`
	DealerID      uuid.UUID   `json:"dealer_id"`
	AssignedRepID pgtype.UUID `json:"assigned_rep_id"`
}

func (q *Queries) AssignContractorToRepByDealer(ctx context.Context, arg AssignContractorToRepByDealerParams) error {
	_, err := q.db.Exec(ctx, assignContractorToRepByDealer, arg.ID, arg.DealerID, arg.AssignedRepID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (dealer_id, email, password_hash, full_name, phone, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, dealer_id, email, password_hash, full_name, phone, role, assigned_rep_id, active, created_at, updated_at
`

type CreateUserParams struct {
	DealerID     uuid.UUID `json:"dealer_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	FullName     string    `json:"full_name"`
	Phone        string    `json:"phone"`
	Role         UserRole  `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DealerID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Phone,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.AssignedRepID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, dealer_id, email, password_hash, full_name, phone, role, assigned_rep_id, active, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.AssignedRepID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, dealer_id, email, password_hash, full_name, phone, role, assigned_rep_id, active, created_at, updated_at FROM users WHERE dealer_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	DealerID uuid.UUID `json:"dealer_id"`
	Email    string    `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.DealerID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.AssignedRepID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContractorsByRep = `-- name: ListContractorsByRep :many
SELECT id, dealer_id, email, password_hash, full_name, phone, role, assigned_rep_id, active, created_at, updated_at FROM users WHERE assigned_rep_id = $1 ORDER BY full_name ASC
`

func (q *Queries) ListContractorsByRep(ctx context.Context, assignedRepID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listContractorsByRep, assignedRepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Phone,
			&i.Role,
			&i.AssignedRepID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByDealer = `-- name: ListUsersByDealer :many
SELECT id, dealer_id, email, password_hash, full_name, phone, role, assigned_rep_id, active, created_at, updated_at FROM users WHERE dealer_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListUsersByDealerParams struct {
	DealerID uuid.UUID `json:"dealer_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListUsersByDealer(ctx context.Context, arg ListUsersByDealerParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByDealer, arg.DealerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Phone,
			&i.Role,
			&i.AssignedRepID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, dealer_id, email, password_hash, full_name, phone, role, assigned_rep_id, active, created_at, updated_at FROM users WHERE dealer_id = $1 AND role = $2 ORDER BY full_name ASC
`

type ListUsersByRoleParams struct {
	DealerID uuid.UUID `json:"dealer_id"`
	Role     UserRole  `json:"role"`
}

func (q *Queries) ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByRole, arg.DealerID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DealerID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Phone,
			&i.Role,
			&i.AssignedRepID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET active = $2, updated_at = now() WHERE id = $1
`

type SetUserActiveParams struct {
	ID     uuid.UUID `json:"id"`
	Active bool      `json:"active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.Active)
	return err
}

const getUserLockoutStatus = `-- name: GetUserLockoutStatus :one
SELECT failed_login_attempts, locked_until FROM users
WHERE dealer_id = $1 AND email = $2
`

type GetUserLockoutStatusParams struct {
	DealerID uuid.UUID `json:"dealer_id"`
	Email    string    `json:"email"`
}

type GetUserLockoutStatusRow struct {
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) GetUserLockoutStatus(ctx context.Context, arg GetUserLockoutStatusParams) (GetUserLockoutStatusRow, error) {
	row := q.db.QueryRow(ctx, getUserLockoutStatus, arg.DealerID, arg.Email)
	var i GetUserLockoutStatusRow
	err := row.Scan(&i.FailedLoginAttempts, &i.LockedUntil)
	return i, err
}

const incrementLoginFailures = `-- name: IncrementLoginFailures :one
UPDATE users
SET failed_login_attempts = failed_login_attempts + 1,
    locked_until = CASE
      WHEN failed_login_attempts + 1 >= 5 THEN now() + interval '15 minutes'
      ELSE locked_until
    END,
    updated_at = now()
WHERE dealer_id = $1 AND email = $2
RETURNING failed_login_attempts, locked_until
`

type IncrementLoginFailuresParams struct {
	DealerID uuid.UUID `json:"dealer_id"`
	Email    string    `json:"email"`
}

type IncrementLoginFailuresRow struct {
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) IncrementLoginFailures(ctx context.Context, arg IncrementLoginFailuresParams) (IncrementLoginFailuresRow, error) {
	row := q.db.QueryRow(ctx, incrementLoginFailures, arg.DealerID, arg.Email)
	var i IncrementLoginFailuresRow
	err := row.Scan(&i.FailedLoginAttempts, &i.LockedUntil)
	return i, err
}

const resetLoginFailures = `-- name: ResetLoginFailures :exec
UPDATE users
SET failed_login_attempts = 0, locked_until = NULL, updated_at = now()
WHERE dealer_id = $1 AND email = $2
`

type ResetLoginFailuresParams struct {
	DealerID uuid.UUID `json:"dealer_id"`
	Email    string    `json:"email"`
}

func (q *Queries) ResetLoginFailures(ctx context.Context, arg ResetLoginFailuresParams) error {
	_, err := q.db.Exec(ctx, resetLoginFailures, arg.DealerID, arg.Email)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name = $2, phone = $3, updated_at = now()
WHERE id = $1
RETURNING id, dealer_id, email, password_hash, full_name, phone, role, assigned_rep_id, active, created_at, updated_at
`

type UpdateUserParams struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Phone    string    `json:"phone"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.FullName, arg.Phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DealerID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.AssignedRepID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
